"""
Django settings for myshop1 project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os

# -------------------------------
# BASE DIRECTORY
# -------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# -------------------------------
# SECURITY
# -------------------------------
SECRET_KEY = 'django-insecure-$uq^ffu8u!!7qf_u%-ogf2#ju0p@xh0&f3f4aaq--h!50)16y+'
DEBUG = True
ALLOWED_HOSTS = []


# -------------------------------
# APPLICATIONS
# -------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'shop',   # agar aapki app ka naam shop hai
]



# -------------------------------
# MIDDLEWARE
# -------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# -------------------------------
# URLS
# -------------------------------
ROOT_URLCONF = 'myshop1.urls'


# -------------------------------
# TEMPLATES
# -------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # project-level templates folder
        'APP_DIRS': True,  # allow app-level templates (shop/templates/)
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# -------------------------------
# WSGI
# -------------------------------
WSGI_APPLICATION = 'myshop1.wsgi.application'


# -------------------------------
# DATABASE
# -------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# -------------------------------
# PASSWORD VALIDATION
# -------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# -------------------------------
# INTERNATIONALIZATION
# -------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# -------------------------------
# STATIC FILES (CSS / JS / Images)
# -------------------------------
STATIC_URL = '/assets/'

# If you have a "shop/static/" folder for your app
STATICFILES_DIRS = [BASE_DIR / 'assets']

# Optional: static root for collectstatic
# STATIC_ROOT = BASE_DIR / "staticfiles"


# -------------------------------
# MEDIA FILES (User uploaded)
# -------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# -------------------------------
# LOGIN / LOGOUT REDIRECTS
# -------------------------------
LOGIN_URL = '/login/'              # Redirect here if user not logged in
LOGIN_REDIRECT_URL = 'home_page'   # Redirect after login
LOGOUT_REDIRECT_URL = '/login/'    # Redirect after logout


# -------------------------------
# DEFAULT PRIMARY KEY
# -------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = 'home_page'   # after login, go to homepage
LOGOUT_REDIRECT_URL = 'login'      # after logout, go back to login page
