# Generated by Django 5.2.4 on 2025-12-26 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_discount_percent_delete_customer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customer_user',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.FloatField(default=0),
        ),
    ]
