# Generated by Django 5.2.4 on 2026-01-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_category_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='customer_user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
