# Generated by Django 5.2.4 on 2026-01-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_productimage_productspec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='caption',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product/gallery/'),
        ),
    ]
